const DEFAULT_SANDBOX_ORG_ID = process.env.DEFAULT_SANDBOX_ORG_ID || '000000000000000000000000';
const DEFAULT_SANDBOX_ORG_SLUG = process.env.DEFAULT_SANDBOX_ORG_SLUG || 'agama-sandbox';
const DEFAULT_SANDBOX_ORG_NAME = process.env.DEFAULT_SANDBOX_ORG_NAME || 'Agama Sandbox';

module.exports = {
  DEFAULT_SANDBOX_ORG_ID,
  DEFAULT_SANDBOX_ORG_SLUG,
  DEFAULT_SANDBOX_ORG_NAME
};
