services:
  - type: web
    name: agama-tech
    rootDir: server
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
